/*
  Action types
 */
export const CAROUSEL_ITEMS_REQUEST = 'CAROUSEL_ITEMS_REQUEST';
export const CAROUSEL_ITEMS_SUCCESS = 'CAROUSEL_ITEMS_SUCCESS';
export const CAROUSEL_ITEMS_FAILURE = 'CAROUSEL_ITEMS_FAILURE';
export const UPDATE_BODY_CLASS = 'UPDATE_BODY_CLASS';
export const COLLECTIONS_REQUEST = 'COLLECTIONS_REQUEST';
export const COLLECTIONS_SUCCESS = 'COLLECTIONS_SUCCESS';
export const COLLECTIONS_FAILURE = 'COLLECTIONS_FAILURE';
