/*
  Action types
 */
export const FETCH_API_TOKEN_SUCCESS = 'FETCH_API_TOKEN_SUCCESS';
export const FETCH_API_TOKEN = 'FETCH_API_TOKEN';
export const CAROUSEL_ITEMS_REQUEST = 'CAROUSEL_ITEMS_REQUEST';
export const CAROUSEL_ITEMS_SUCCESS = 'CAROUSEL_ITEMS_SUCCESS';
export const CAROUSEL_ITEMS_FAILURE = 'CAROUSEL_ITEMS_FAILURE';
export const COLLECTIONS_REQUEST = 'COLLECTIONS_REQUEST';
export const COLLECTIONS_SUCCESS = 'COLLECTIONS_SUCCESS';
export const COLLECTIONS_FAILURE = 'COLLECTIONS_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_TOGGLE = 'SEARCH_TOGGLE';
