#!/bin/bash

export REACT_APP_ELASTICSEARCH_PROXY_BASE=$(aws ssm get-parameter --name /stack-glaze/react_app_elasticsearch_proxy_base | jq -r '.Parameter.Value')
export REACT_APP_DONUT_URL=$(aws ssm get-parameter --name /stack-glaze/react_app_donut_url | jq -r '.Parameter.Value')
export REACT_APP_IIIF_LOGIN_URL=$(aws ssm get-parameter --name /stack-glaze/react_app_iiif_login_url | jq -r '.Parameter.Value')
export REACT_APP_SHARED_ITEM_PROXY_URL=$(aws ssm get-parameter --name /stack-glaze/react_app_shared_item_proxy_url | jq -r '.Parameter.Value')
S3_BUCKET=$(aws ssm get-parameter --name /dc/s3_bucket | jq -r '.Parameter.Value')

echo "REACT_APP_ELASTICSEARCH_PROXY_BASE=$REACT_APP_ELASTICSEARCH_PROXY_BASE REACT_APP_DONUT_URL=$REACT_APP_DONUT_URL REACT_APP_IIIF_LOGIN_URL=$REACT_APP_IIIF_LOGIN_URL REACT_APP_SHARED_ITEM_PROXY_URL=$REACT_APP_SHARED_ITEM_PROXY_URL S3_BUCKET=$S3_BUCKET"

yarn install
yarn build
aws s3 sync --delete --acl public-read ./build/ s3://${S3_BUCKET}/
