#!/bin/bash

REACT_APP_ELASTICSEARCH_PROXY_BASE=$(aws ssm get-parameter --name /stack-glaze/react_app_elasticsearch_proxy_base | jq -r '.Parameter.Value')
REACT_APP_DONUT_URL=$(aws ssm get-parameter --name /stack-glaze/react_app_donut_url | jq -r '.Parameter.Value')
S3_BUCKET=$(aws ssm get-parameter --name /stack-glaze/s3_bucket | jq -r '.Parameter.Value')

rsync -ar --exclude "node_modules/*" ${SOURCE}/ deploy
cd deploy
yarn install
yarn build
aws s3 sync --delete --acl public-read ./build/ s3://${S3_BUCKET}/
